name: Welcome Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'


jobs:
  welcome_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send welcome message
      run: echo "Thank you for pushing to this repository!"

    - name: Checkout
      uses: actions/checkout@v4.1.1
  