name: Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
      
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
       scan-type: 'fs'
       format: 'table'
       output: 'trivy-report.txt'
        
    - name: Read Trivy report
      id: read_report
      run: |
        content=$(cat trivy-report.txt)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=content::$content"
      shell: bash
        
    - name: Send Trivy report to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,action,eventName,ref,workflow,job,executor
        text: |
          GitHub Action build result: ${{ job.status }}
          ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
          Trivy Report:
          ${{ steps.read_report.outputs.content }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
