name: Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
      
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   

    - name: Checkout
      uses: actions/checkout@v4.1.1
  
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
       scan-type: 'fs'
       format: 'table'
       output: 'trivy-report.txt'
        
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
    # For posting a rich message using Block Kit
       payload: |
         {
           "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
           "blocks": [
             {
               "type": "section",
               "text": {
                 "type": "mrkdwn",
                "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
               }
             }
           ]
         }
      env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


      
      
  
