name: Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
      
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   

    - name: Checkout
      uses: actions/checkout@v4.1.1
  
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
       scan-type: 'fs'
       format: 'table'
       output: 'trivy-report.txt'
        
    - name: Send Trivy report to Slack
      uses: 8398a7/action-slack@v3
      with:
       status: ${{ job.status }}
       fields: repo,commit,author,action,eventName,ref,workflow,job,executor



      
      
  
