name: Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
      
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
   
  
    - name: Checkout code
      uses: actions/checkout@v2



    - name: Create docs directory and save table
      run: |
            mkdir -p docs
            echo "" > docs/table.txt
      

      
    - name: Build an image from Dockerfile
      run: |
         docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      id: table
      with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          output: 'table.txt'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
   
    - name: Save Trivy output to file
      if: ${{ failure() }}   
      run: |
       echo "${{ steps.table.outputs.stdout }}" > docs/table.txt

    - name: Print the content of the file
      if: ${{ failure() }}
      run: cat docs/table.txt

      
    
    - name: Slack Notification
      if: ${{ failure() }} 
      uses: rtCamp/action-slack-notify@v2
      env:
        
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: |
         Name:ZhangSibo
         Matriculation：A0287263W
         Email:E1285209@u.nus.edu
         Git:
         Image:
        
        SLACK_TITLE: Image build and signed
        SLACK_USERNAME: CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    - uses: MeilCli/slack-upload-file@v3
      if: ${{ failure() }} 
      with:
          slack_token: ${{ secrets.TOKEN }}
          channel_id: ${{ secrets.CHANNEL }}
          
          file_path: 'docs/table.txt'
          
          title: 'ZHANG SIBO'
          initial_comment: 'post by slack-upload-file'
         

    - uses: MeilCli/slack-upload-file@v3
      if: ${{ failure() }}
      with:
          slack_token: ${{ secrets.TOKEN }}
          channel_id: ${{ secrets.CHANNEL }}
          content: 'file content'
          file_path: './docs/table.txt'
          file_type: 'plain'
          file_name: 'table.txt'
          title: 'title of file'
          initial_comment: 'post by slack-upload-file'
         

        
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          push: true
          tags: blueeyesandwhitedragon/test:${{github.sha}}
    - name: Sign image with a key
      run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
          TAGS: blueeyesandwhitedragon/test:${{github.sha}}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGNKEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGNPASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
