name: Welcome Workflow

on: push

jobs:
  welcome_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send welcome message
      run: echo "Thank you for pushing to this repository!"
