name: Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
      
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
      id: scan
      with:
       scan-type: 'fs'
       format: 'table'
       output: 'trivy-report.txt'

    - name: Print scan results
      run: cat trivy-report.txt


    - name: Read scan table
      id: read_table
      run: |
        content=$(cat trivy-report.txt) 
        echo "::set-output name=table::$content"
      shell: bash

    
        
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
   
        payload: |
         {
           "text": "Test message from GitHub Actions"
         }

    env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
